--- #YAML:1.0
name:                Handel-Storage-RDBO
version:             0.99_16
abstract:            RDBO schema storage layer for cart/order/item reads/writes
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Christopher H. Laco <claco@chrislaco.com>
distribution_type:   module
requires:     
    Handel:                        1.0
    Rose::DB:                      0
    Rose::DB::Object:              0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
