--- #YAML:1.0
name: Handel-Storage-RDBO
version: 0.01_02
abstract: RDBO schema storage layer for cart/order/item reads/writes
license: perl
generated_by: ExtUtils::MakeMaker version 6.30_01
author: Christopher H. Laco <claco@chrislaco.com>
distribution_type: module
requires:     
  Handel: 1.0
  Rose::DB: 0.732
  Rose::DB::Object: 0.759
  Clone: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0.61
recommends:
  Pod::Coverage: 0.14
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
  Test:Strict: 0.05
  Test::Spelling: 0.10
  Test::NoTabs: 0.01
  Test::Perl::Critic: 0.07
  Test::CheckManifest: 0.07
meta-spec:
  url: <http://module-build.sourceforge.net/META-spec-new.html>;
  version: 1.1
